// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq9M_JRDBcnzz2S_1ipBZyg05DnFN9AEA',
    appId: '1:398850139194:web:a1c4705d83793338c70103',
    messagingSenderId: '398850139194',
    projectId: 'resume-ai-8888f',
    authDomain: 'resume-ai-8888f.firebaseapp.com',
    storageBucket: 'resume-ai-8888f.firebasestorage.app',
    measurementId: 'G-T65NHRPR51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw74_2Z2IeH7ooBZYfEaELw-vffKv13c0',
    appId: '1:398850139194:android:646e9fb0f42e0213c70103',
    messagingSenderId: '398850139194',
    projectId: 'resume-ai-8888f',
    storageBucket: 'resume-ai-8888f.firebasestorage.app',
  );
}
